site_name: HashData
theme: readthedocs 

pages:
- 欢迎使用: 'index.md'
- "<&product-name> 系统概述": 'overview.md'
- "" : 'management.md'
- "" : 'sql-ref.md'
    - "" : 'sql-ref/sql-ref-summary.md'
- "" : 'meta-ref.md'
    - "" : 'meta-ref/meta-ref-all.md'
# - "" : 'func-ref.md'
# - "" : 'guc-ref.md'
- "" : 'history.md'

